services:
  wings:
    image: ghcr.io/pelican-dev/wings:latest
    container_name: pelican_wings
    restart: always
    networks:
      - default_nw
    tty: true
    environment:
      WINGS_UID: 988
      WINGS_GID: 988
      WINGS_USERNAME: pelican
    volumes:
      - ./config.yml:/etc/pelican/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./backups/:/var/lib/pelican/backups/
      - pelican-wings-logs:/var/log/pelican/

volumes:
  pelican-wings-logs:

networks:
  default_nw:
    external: true
