
map $http_upgrade $connection_upgrade {
    default upgrade;
    ""      close;
}

map $host $backend {
    default            http://not_found;
    pp.holocons.xyz    http://panel:80;
    pw.holocons.xyz    http://wings:8080;
    stats.holocons.xyz http://172.18.0.1:8804;
}
