
server {
    listen 443 ssl;
    server_name stats.holocons.xyz;

    access_log /var/log/nginx/plan.app-access.log;
    error_log /var/log/nginx/plan.app-error.log error;

    include /etc/nginx/snippets/security.conf;
    add_header X-Robots-Tag none;

    location / {
        proxy_pass $backend;
        include /etc/nginx/snippets/proxy-identity.conf;
    }
}
